### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by nm17** [nm17/netschoolapi#3]
```
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 11, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/trio/_core/_run.py", line 1804, in run
    raise runner.main_task_outcome.error
  File "<string>", line 8, in main
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.7/site-packages/netschoolapi/client.py", line 96, in login
    int(re.search(r'userId = "(\d+)"', resp.text, re.U).group(1)) - 2
AttributeError: 'NoneType' object has no attribute 'group'

[Program finished]
```

**Comment by nm17** [comment]
Кажись API опять изменилось...

**Comment by nm17** [comment]
Вроде работает... Закрываю.
